name: daily-report

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Scrape Winterthur
        run: python scrape_winterthurer_zeitung.py
      - name: Get Parkings Zürich
        run: python parking_zuerich.py
      - name: Commit and push if the data has changed
        run: |
          git config --global user.name 'plotti2k1'
          git config --global user.email 'plotti2k1@users.noreply.github.com'
          git commit -am "Automated report"
          git push
